### PR TITLE
Fixes rpmbuild failure on Mac OSX.

### PR DESCRIPTION
**Pull request by pepper-ankan**
This fixes a build problem on a developer's Mac box.  The fix is explained in details in the comments added to the two changed files.

### CODE REVIEW

**Comment by ssuchter** [comment]
I agree, this looks good.

**Comment by ssuchter** [comment]
Ankan, you should merge this now that you have approval. (Just like committing and pushing in hg after you have review approval.)

**Comment by pepper-ankan** [comment]
Done.

I used:

`$ git fetch origin`
`$ git checkout next_pepperdata`
`$ git merge next_pepperdata-ankan-osxfix`
`$ git push origin next_pepperdata`

Final status:
On branch next_pepperdata
Your branch is up-to-date with 'origin/next_pepperdata'.
nothing to commit, working tree clean

**Comment by pepper-ankan** [comment]
Deleted topic branch `next_pepperdata-ankan-osxfix`, now that it was merged successfully with `next_pepperdata`:

`$ git branch -d next_pepperdata-ankan-osxfix`
`Deleted branch next_pepperdata-ankan-osxfix (was 6b7ec13).`

**Comment by pepper-ankan** [comment]
Also deleted _remote_ topic branch `next_pepperdata-ankan-osxfix`, now that it was merged successfully with `next_pepperdata`:

`$ git push origin --delete next_pepperdata-ankan-osxfix`
`To github.com:pepperdata/opentsdb.git`
` - [deleted]         next_pepperdata-ankan-osxfix`

**Pull request merged**
